### ISSUE TITLE
Handling post for oauth?

### ISSUE THREAD

**Issue by legopin** [tylerlong/ringcentral-token-generator#3]
I was following the instructions found here: https://medium.com/ringcentral-developers/latest-glip-bot-provision-flow-a626a8dd0d98

However during step 2 the 3-legged oauth flow would fail. 
Upon inspection the ngrok log shows that the RingCentral server actually sent the oauth request as a HTTP POST request, while the application source code seems to only support HTTP GET. 

Was this a recent change on RingCentral's part?

**Comment by tylerlong** [comment]
I think so.  Something was changed on RingCentral server side.

I am pretty sure that this tool worked before. But now it doesn't.

**Comment by tylerlong** [comment]
@legopin  

For private bot, you don't need this tool.  And this tool doesn't work for private bots due to the recent change on RingCentral server side.

Just set redirect uri to https://www.ringcentra.com and you get get the token from the GUI after adding the bot.

For public bots, this tool still works.
